### ISSUE TITLE
how and where to use it?

### ISSUE THREAD

**Issue by wiztensai** [14v/svg-non-stop#2]
sorry i confuse to use it. i have non stop issue too.

**Comment by 14v** [comment]
There is example in readme. Please clarify what problem are you experiencing.

**Comment by wiztensai** [comment]
first i think, i will import NonStop.kt then i will use it in my fragment:

`NonStop.processSvg(nodeList)`

i dont understand to create nodeList. or another how?

**Comment by 14v** [comment]
This utility is not for use in Android app. It is only for importing SVG as vector assets. Please check readme.

**Comment by agustinvaca** [comment]
How can you use this in Windows? Or is this only for Linux?

**Comment by 14v** [comment]
There is bat file in zip, use it with same params like in Readme.

**Comment by agustinvaca** [comment]
> There is bat file in zip, use it with same params like in Readme.

Thank you! For some reason I could not do it from the svg-non-stop folder, I had to cd into bin, specify "svg-non-stop.bat" and then specify the FULL PATH to my svg file.

Just some advice for any newbies like me :)
