### ISSUE TITLE
Build doesn't produce any artifacts in `bin/`

### ISSUE THREAD

**Issue by interfect** [14v/svg-non-stop#3]
The README suggests that after I build there will be a program to run in `bin/`, but I've tried several Gradle tasks including `./gradlew build` and `./gradlew distZip` and I haven't gotten a `bin/` directory.

How do I build and run the tool?

**Comment by s3r6** [comment]
Use `assemble` task and you will get `build/distributions/svg-non-stop-1.0.1.zip` archive. Please comment if this works for you.
