### ISSUE TITLE
Allow radialGradient to be processed

### ISSUE THREAD

**Issue by marcohc** [14v/svg-non-stop#5]
Hi,

it you change the line 135 of _NonStop.kt_ for this:

`private fun Node.isGradient(): Boolean = nodeName == "linearGradient" || nodeName == "radialGradient"`

It'll allow radialGradient to be included as well in the processing.

Thanks for the lib!

**Comment by 14v** [comment]
Please provide sample SVG to check on after making your change

**Comment by marcohc** [comment]
Ok, here it comes (it's a .svg file, but had to rename it to be able to upload it):

[radial_gradient.txt](https://github.com/14v/svg-non-stop/files/7224606/radial_gradient.txt)

**Comment by 14v** [comment]
Done, please check new release. File is processed correct, but there are other issues not caused by gradient when importing in IDE.
