### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cypherdare** [14v/svg-non-stop#6]
Can you add a license? I'm interested in forking it and making a JAR library so it can be used in a public Gradle plugin.

**Comment by 14v** [comment]
Done. Please provide here a link to plugin when it will be ready as I am interested how it will be used.

**Comment by cypherdare** [comment]
Thank you! I'm still tinkering at this point. I'd like to see how far I can automate getting my source SVGs converted to usable drawable resources with a Gradle configuration object, sort of like how [this other plugin](https://github.com/CypherCove/IconDivvy/) I made works.

**Comment by cypherdare** [comment]
I have updated my plugin [IconDivvy](https://github.com/CypherCove/IconDivvy/) to include vector file processing (rather than create a separate plugin). It uses a cloned copy of svg-non-stop. It provides a Gradle task that takes a directory containing SVG files, applies your gradient fix, and then converts them into Android xml vector drawables, placed in the `drawable` directory in the project. So, you can set up your gradle build task to automatically include the latest changes to your source SVGs.
